llm:
  api_type: "ark" 
  base_url: ""
  api_key: "94726836-59af-47e0-8893-46f1944b03d3"
  model: "deepseek-r1-250120"  
  proxy: "" 
  pricing_plan: "" 



# RAG Embedding.
# For backward compatibility, if the embedding is not set and the llm's api_type is either openai or azure, the llm's config will be used. 
embedding:
  api_type: "openai" # openai / azure / gemini / ollama etc. Check EmbeddingType for more options.
  base_url: ""
  api_key: "94726836-59af-47e0-8893-46f1944b03d3"
  model: "doubao-embedding-large-text-240915"
  api_version: ""
  embed_batch_size: 100
  dimensions: # output dimension of embedding model

# Role's custom configuration
roles:
  - role: "ProductManager" # role's className or role's role_id
    llm:
      api_type: "ark" 
      base_url: ""
      api_key: "94726836-59af-47e0-8893-46f1944b03d3"
      model: "deepseek-r1-250120"  
  - role: "Architect"
    llm:
      api_type: "ark"  # or azure / ollama / open_llm etc. Check LLMType for more options
      base_url: ""
      api_key: "94726836-59af-47e0-8893-46f1944b03d3"
      model: "deepseek-r1-250120"  
  - role: "ProjectManager"
    llm:
      api_type: "ark"
      base_url: ""
      api_key: "94726836-59af-47e0-8893-46f1944b03d3"
      model: "deepseek-r1-250120"
  - role: "Engineer"
    llm:
      api_type: "ark"
      base_url: ""
      api_key: "94726836-59af-47e0-8893-46f1944b03d3"
      model: "deepseek-r1-250120"

repair_llm_output: true  # when the output is not a valid json, try to repair it

proxy: "YOUR_PROXY"  # for tools like requests, playwright, selenium, etc.

search:
  api_type: "google"
  api_key: "YOUR_API_KEY"
  cse_id: "YOUR_CSE_ID"

browser:
  engine: "playwright"  # playwright/selenium
  browser_type: "chromium"  # playwright: chromium/firefox/webkit; selenium: chrome/firefox/edge/ie

mermaid:
  engine: "pyppeteer"
  pyppeteer_path: "/Applications/Google Chrome.app"

redis:
  host: "YOUR_HOST"
  port: 32582
  password: "YOUR_PASSWORD"
  db: "0"

s3:
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"
  endpoint: "YOUR_ENDPOINT"
  secure: false
  bucket: "test"

exp_pool:
  enabled: false
  enable_read: false 
  enable_write: false
  persist_path: .chroma_exp_data # The directory.
  retrieval_type: bm25 # Default is `bm25`, can be set to `chroma` for vector storage, which requires setting up embedding.
  use_llm_ranker: true # Default is `true`, it will use LLM Reranker to get better result.
  collection_name: experience_pool  # When `retrieval_type` is `chroma`, `collection_name` is the collection name in chromadb.

role_zero:
  enable_longterm_memory: false # Whether to use long-term memory. Default is `false`.
  longterm_memory_persist_path: .role_memory_data # The directory to save data.
  memory_k: 200 # The capacity of short-term memory.
  similarity_top_k: 5 # The number of long-term memories to retrieve.
  use_llm_ranker: false # Whether to use LLM Reranker to get better result. Default is `false`.

azure_tts_subscription_key: "YOUR_SUBSCRIPTION_KEY"
azure_tts_region: "eastus"

iflytek_api_id: "YOUR_APP_ID"
iflytek_api_key: "YOUR_API_KEY"
iflytek_api_secret: "YOUR_API_SECRET"

ohm_tti_url: "YOUR_MODEL_URL"

omniparse:
    api_key: "YOUR_API_KEY"
    base_url: "YOUR_BASE_URL"

models:
  default:
    api_type: "ark" 
    base_url: ""
    api_key: "94726836-59af-47e0-8893-46f1944b03d3"
    model: "deepseek-r1-250120"  
    proxy: "" 
    pricing_plan: "" 
